name: Build

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Build
        uses: actions/setup-node@v7
        with:
          node-version: 24.19.0
          cache: npm
      - run: npm ci
      - run: npm run build

      - name: Zip package
        run: |
          mkdir -p release
          zip -jr release/send_vrc.zip ./dist/*

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          files: "release/send_vrc.zip"
          prerelease: ${{ contains(github.ref, '-beta') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
