name: Validate renovate.json

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  renovate-config-validator:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.16.0
          cache: npm

      - name: Install Renovate CLI
        run: npm install -g renovate

      - name: Validate renovate.json
        run: renovate-config-validator
