name: Validate renovate.json

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  renovate-config-validator:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24.18.0
          cache: npm

      - name: Install Renovate CLI
        run: npm install -g renovate

      - name: Validate renovate.json
        run: renovate-config-validator
